logging:
  level: INFO
  loggers:
    net.bosselaar.seprinter: DEBUG

streamelements:
  jwtToken: "insert SE JWT token here. Go to https://streamelements.com/dashboard/account/channels and enable 'show secrets'"

printer:
  dpi: 203
  paperWidth: 58
  printableWidth: 48
  rotate: false